package: redaktionsassistent
version: 1.0.3
author: Wolfgang Bund
supportpage: www.redaxo.org/de/forum/

page:
    title: Redaktionsassistent
    pjax: true
    icon: rex-icon rex-icon-system
    subpages:
        tasks:
            title: Bearbeitung
        assign_articles:
            title: Artikel zuordnen
        settings:
            title: Einstellungen
requires:
    redaxo: '^5.5'
    packages:
        structure: '^2.0'
        structure_plus: '>0,<9'
        yform/manager: '>=3'
